"use client";

import { useState } from "react";

const today =
  new Date().toLocaleDateString("ko-KR");

const jewelryTypes = [
"Ring",
"Necklace",
"Earrings",
];

const metals = [
"Silver",
"14K Gold",
"18K Gold",
"Platinum",
];

const stones = [
"None",
"Diamond",
"Ruby",
"Sapphire",
"Rhodolite Garnet",
"Moonstone",
];

const ringBands = [
"Classic",
"Wave",
"Flat",
"Twist",
];

const chainStyles = [
"Cable",
"Box",
"Rope",
"Snake",
];

const chainLengths = [
"40cm",
"45cm",
"50cm",
"60cm",
];

const earringStyles = [
"Stud",
"Drop",
"Hoop",
];

const postMaterials = [
  "925 Silver",
  "Surgical Steel",
  "14K Gold",
  "18K Gold",
];

export default function StudioPage() {

  const resetDesign = () => {

    setType("Necklace");
  
    setMetal("Silver");
  
    setStone("None");
  
    setBand("Classic");
  
    setSize(12);
  
    setChainStyle("Cable");
  
    setChainLength("45cm");
  
    setEarringStyle("Stud");
  
    setOrderSheet("");
  };
  
  const saveDesign = () => {

    const draft = {
      type,
      metal,
      stone,
      band,
      size,
      chainStyle,
      chainLength,
      earringStyle,
    };
  
    localStorage.setItem(
      "voutiqDraft",
      JSON.stringify(draft)
    );
  
    alert("Design saved");
  };

const [type, setType] =
useState("Necklace");

const [metal, setMetal] =
useState("Silver");

const [stone, setStone] =
useState("None");

const [band, setBand] =
useState("Classic");

const [chainStyle, setChainStyle] =
useState("Cable");

const [chainLength, setChainLength] =
useState("45cm");

const [earringStyle, setEarringStyle] =
useState("Stud");

const [postMaterial, setPostMaterial] =
  useState("925 Silver");

const [size, setSize] =
useState(12);

const [orderSheet, setOrderSheet] =
  useState("");

const [customerName, setCustomerName] =
  useState("");

const [customerPhone, setCustomerPhone] =
  useState("");

const [customerEmail, setCustomerEmail] =
  useState("");

const exportOrderSheet = () => {

    const today =
      new Date().toLocaleDateString("ko-KR");
  
    const content = `
  STONIN BESPOKE REQUEST
  ────────────────────
  
  Date
  ${today}
  
  Jewelry Type
  ${type}
  
  Metal
  ${metal}
  
  Stone
  ${stone}
  
  ${type === "Ring" ? `
  Band Style
  ${band}
  
  Ring Size
  ${size}호
  ` : ""}
  
  ${type === "Necklace" ? `
  Chain Style
  ${chainStyle}
  
  Chain Length
  ${chainLength}
  ` : ""}
  
  ${type === "Earrings" ? `
  Earring Style
  ${earringStyle}
  
  Post Material
  ${postMaterial}
  ` : ""}
  
  ────────────────────
  
  Generated by Studio
  Powered by VOUTIQ™
  `;
  
    setOrderSheet(content);
  
    navigator.clipboard.writeText(content);
  };
  const requestProduction = () => {

    const requestId =
      `STN-${Date.now()}`;
  
    const subject =
      encodeURIComponent(
        `[STONIN] ${requestId}`
      );
  
    const body =
      encodeURIComponent(
  `
  Request ID
  ${requestId}
  
  ${orderSheet}
  `
      );
  
    window.location.href =
      `mailto:soyoung@draft.best?subject=${subject}&body=${body}`;
  };

const downloadTxt = () => {

    const blob =
      new Blob(
        [orderSheet],
        { type: "text/plain" }
      );
  
    const url =
      URL.createObjectURL(blob);
  
    const a =
      document.createElement("a");
  
    a.href = url;
  
    a.download =
      `stonin-request-${Date.now()}.txt`;
  
    a.click();
  
    URL.revokeObjectURL(url);
  };

return ( <main className="mx-auto max-w-7xl px-8 py-12">

  <div className="mb-12">

    <h1 className="text-5xl font-semibold">
      Studio
    </h1>

    <p className="mt-4 text-[#8A7A72]">
      Configure your future piece.
    </p>

  </div>

  <div className="grid grid-cols-2 gap-12">
    <div className="flex min-h-[700px] items-center justify-center rounded-xl bg-[#F4EBE8]">

      <div className="text-center">

        <div className="mb-8 text-8xl">
          {type === "Ring" && "💍"}
          {type === "Necklace" && "📿"}
          {type === "Earrings" && "✨"}
        </div>

        <div>{type}</div>
        <div>{metal}</div>
        <div>{stone}</div>

        {type === "Ring" && (
          <>
            <div>{band}</div>
            <div>{size}호</div>
          </>
        )}

        {type === "Necklace" && (
          <>
            <div>{chainStyle}</div>
            <div>{chainLength}</div>
          </>
        )}

        {type === "Earrings" && (
          <>
            <div>{earringStyle}</div>
            <div>{postMaterial}</div>
          </>
        )}

      </div>

    </div>

    <div className="space-y-8">

    <div className="border-t border-[#D8C7BD] pt-8 mt-8">

<p
  className="
  mb-6
  text-sm
  uppercase
  tracking-[0.2em]
  text-[#B49A8D]
  "
>
  Customer Information
</p>

  <label className="mb-2 block">
    Customer Name
  </label>

  <input
    type="text"
    value={customerName}
    onChange={(e)=>
      setCustomerName(e.target.value)
    }
    className="w-full border p-3"
  />

</div>

<div>

  <label className="mb-2 block">
    Phone Number
  </label>

  <input
    type="text"
    value={customerPhone}
    onChange={(e)=>
      setCustomerPhone(e.target.value)
    }
    className="w-full border p-3"
  />

</div>

<div>

  <label className="mb-2 block">
    Email Address
  </label>

  <input
    type="email"
    value={customerEmail}
    onChange={(e)=>
      setCustomerEmail(e.target.value)
    }
    className="w-full border p-3"
  />

</div>
<div className="border-t border-[#D8C7BD] pt-8 mt-8">

<p
  className="
  mb-6
  text-sm
  uppercase
  tracking-[0.2em]
  text-[#B49A8D]
  "
>
  CONFIGURATION
</p>

      <div>

        <label className="mb-2 block">
          Jewelry Type
        </label>

        <select
          className="w-full border p-3"
          value={type}
          onChange={(e)=>
            setType(e.target.value)
          }
        >
          {jewelryTypes.map(item=>(
            <option key={item}>
              {item}
            </option>
          ))}
        </select>

      </div>

      <div>

        <label className="mb-2 block">
          Metal
        </label>

        <select
          className="w-full border p-3"
          value={metal}
          onChange={(e)=>
            setMetal(e.target.value)
          }
        >
          {metals.map(item=>(
            <option key={item}>
              {item}
            </option>
          ))}
        </select>

      </div>

      <div>

        <label className="mb-2 block">
          Center Stone
        </label>

        <select
          className="w-full border p-3"
          value={stone}
          onChange={(e)=>
            setStone(e.target.value)
          }
        >
          {stones.map(item=>(
            <option key={item}>
              {item}
            </option>
          ))}
        </select>

      </div>

      {type === "Ring" && (
        <>
          <div>

            <label className="mb-2 block">
              Band Style
            </label>

            <select
              className="w-full border p-3"
              value={band}
              onChange={(e)=>
                setBand(e.target.value)
              }
            >
              {ringBands.map(item=>(
                <option key={item}>
                  {item}
                </option>
              ))}
            </select>

          </div>

          <div>

            <label className="mb-2 block">
              Ring Size
            </label>

            <input
              type="number"
              value={size}
              onChange={(e)=>
                setSize(Number(e.target.value))
              }
              className="w-full border p-3"
            />

          </div>
        </>
      )}

      {type === "Necklace" && (
        <>
          <div>

            <label className="mb-2 block">
              Chain Style
            </label>

            <select
              className="w-full border p-3"
              value={chainStyle}
              onChange={(e)=>
                setChainStyle(e.target.value)
              }
            >
              {chainStyles.map(item=>(
                <option key={item}>
                  {item}
                </option>
              ))}
            </select>

          </div>

          <div>

            <label className="mb-2 block">
              Chain Length
            </label>

            <select
              className="w-full border p-3"
              value={chainLength}
              onChange={(e)=>
                setChainLength(e.target.value)
              }
            >
              {chainLengths.map(item=>(
                <option key={item}>
                  {item}
                </option>
              ))}
            </select>

          </div>
        </>
      )}
</div>
      {type === "Earrings" && (
        <div>

          <label className="mb-2 block">
            Earring Style
          </label>

          <select
            className="w-full border p-3"
            value={earringStyle}
            onChange={(e)=>
              setEarringStyle(e.target.value)
            }
          >
            {earringStyles.map(item=>(
              <option key={item}>
                {item}
              </option>
            ))}
          </select>
          </div>
      )}

      {type === "Earrings" && (
        <div>
          
          <label className="mb-2 block">
            Post Material
          </label>

          <select
            className="w-full border p-3"
            value={postMaterial}
            onChange={(e)=>
              setPostMaterial(e.target.value)
            }
          >
            {postMaterials.map(item=>(
              <option key={item}>
                {item}
              </option>
            ))}
          </select>
          </div>
      )}




      <div className="border-t pt-8">

      <div className="grid grid-cols-3 gap-4 mb-4">

      <button
          className="
          rounded-lg
          border
          border-[#D8C7BD]
          bg-white
          py-4
          "
          onClick={resetDesign}
        >
          Reset
        </button>

        <button
          className="
          rounded-lg
          border
          border-[#D8C7BD]
          bg-white
          py-4
          "
          onClick={saveDesign}
        >
          Save Design
        </button>

        <button
          onClick={exportOrderSheet}
          className="
          rounded-lg
          border
          border-[#D8C7BD]
          bg-white
          py-4
          "
        >
          Generate Order Sheet
        </button>

      </div>
      

<p
  className="
  mb-4
  text-sm
  italic
  text-[#8A7A72]
  "
>
  Your request will be reviewed
  before production begins.
  We will contact you after
  confirming the details.
</p>
      <button
        onClick={requestProduction}
        className="
        w-full
        rounded-lg
        bg-black
        py-4
        text-white
        "
      >
        Request Production
      </button>

      </div>

    </div>

  </div>

  {orderSheet && (

    <section className="mt-12">

      <h2 className="mb-4 text-2xl font-semibold">
        Request Preview
      </h2>

      <textarea
        readOnly
        value={orderSheet}
        className="
        w-full
        h-[400px]
        rounded-xl
        border
        border-[#D8C7BD]
        bg-white
        p-6
        font-mono
        text-sm
        "
      />

    </section>

    )}

</main>

);
}
